
export const regions = [
  {
    name: 'Central',
    th: 'ภาคกลาง',
    value: 'central',
    provinces: [
      { name: 'Ang Thong', th: 'อ่างทอง', value: 'ang_thong' },
      { name: 'Bangkok', th: 'กรุงเทพมหานคร', value: 'bangkok' },
      { name: 'Chai Nat', th: 'ชัยนาท', value: 'chai_nat' },
      { name: 'Lop Buri', th: 'ลพบุรี', value: 'lop_buri' },
      { name: 'Nakhon Nayok', th: 'นครนายก', value: 'nakhon_nayok' },
      { name: 'Nakhon Pathom', th: 'นครปฐม', value: 'nakhon_pathom' },
      { name: 'Nonthaburi', th: 'นนทบุรี', value: 'nonthaburi' },
      { name: 'Pathum Thani', th: 'ปทุมธานี', value: 'pathum_thani' },
      { name: 'Phra Nakhon Si Ayutthaya', th: 'พระนครศรีอยุธยา', value: 'phra_nakhon_si_ayutthaya' },
      { name: 'Samut Prakan', th: 'สมุทรปราการ', value: 'samut_prakan' },
      { name: 'Samut Sakhon', th: 'สมุทรสาคร', value: 'samut_sakhon' },
      { name: 'Samut Songkhram', th: 'สมุทรสงคราม', value: 'samut_songkhram' },
      { name: 'Saraburi', th: 'สระบุรี', value: 'saraburi' },
      { name: 'Sing Buri', th: 'สิงห์บุรี', value: 'sing_buri' },
    ],
  },
  {
    name: 'East',
    th: 'ภาคตะวันออก',
    value: 'east',
    provinces: [
      { name: 'Chachoengsao', th: 'ฉะเชิงเทรา', value: 'chachoengsao' },
      { name: 'Chanthaburi', th: 'จันทบุรี', value: 'chanthaburi' },
      { name: 'Chon Buri', th: 'ชลบุรี', value: 'chon_buri' },
      { name: 'Prachin Buri', th: 'ปราจีนบุรี', value: 'prachin_buri' },
      { name: 'Rayong', th: 'ระยอง', value: 'rayong' },
      { name: 'Sa Kaeo', th: 'สระแก้ว', value: 'sa_kaeo' },
      { name: 'Trat', th: 'ตราด', value: 'trat' },
    ],
  },
  {
    name: 'North',
    th: 'ภาคเหนือ',
    value: 'north',
    provinces: [
      { name: 'Chiang Mai', th: 'เชียงใหม่', value: 'chiang_mai' },
      { name: 'Chiang Rai', th: 'เชียงราย', value: 'chiang_rai' },
      { name: 'Kamphaeng Phet', th: 'กำแพงเพชร', value: 'kamphaeng_phet' },
      { name: 'Lampang', th: 'ลำปาง', value: 'lampang' },
      { name: 'Lamphun', th: 'ลำพูน', value: 'lamphun' },
      { name: 'Mae Hong Son', th: 'แม่ฮ่องสอน', value: 'mae_hong_son' },
      { name: 'Nakhon Sawan', th: 'นครสวรรค์', value: 'nakhon_sawan' },
      { name: 'Nan', th: 'น่าน', value: 'nan' },
      { name: 'Phayao', th: 'พะเยา', value: 'phayao' },
      { name: 'Phetchabun', th: 'เพชรบูรณ์', value: 'phetchabun' },
      { name: 'Phichit', th: 'พิจิตร', value: 'phichit' },
      { name: 'Phitsanulok', th: 'พิษณุโลก', value: 'phitsanulok' },
      { name: 'Phrae', th: 'แพร่', value: 'phrae' },
      { name: 'Sukhothai', th: 'สุโขทัย', value: 'sukhothai' },
      { name: 'Tak', th: 'ตาก', value: 'tak' },
      { name: 'Uthai Thani', th: 'อุทัยธานี', value: 'uthai_thani' },
      { name: 'Uttaradit', th: 'อุตรดิตถ์', value: 'uttaradit' },
    ],
  },
  {
    name: 'Northeast',
    th: 'ภาคตะวันออกเฉียงเหนือ',
    value: 'northeast',
    provinces: [
      { name: 'Amnat Charoen', th: 'อำนาจเจริญ', value: 'amnat_charoen' },
      { name: 'Bueng Kan', th: 'บึงกาฬ', value: 'bueng_kan' },
      { name: 'Buri Ram', th: 'บุรีรัมย์', value: 'buri_ram' },
      { name: 'Chaiyaphum', th: 'ชัยภูมิ', value: 'chaiyaphum' },
      { name: 'Kalasin', th: 'กาฬสินธุ์', value: 'kalasin' },
      { name: 'Khon Kaen', th: 'ขอนแก่น', value: 'khon_kaen' },
      { name: 'Loei', th: 'เลย', value: 'loei' },
      { name: 'Maha Sarakham', th: 'มหาสารคาม', value: 'maha_sarakham' },
      { name: 'Mukdahan', th: 'มุกดาหาร', value: 'mukdahan' },
      { name: 'Nakhon Phanom', th: 'นครพนม', value: 'nakhon_phanom' },
      { name: 'Nakhon Ratchasima', th: 'นครราชสีมา', value: 'nakhon_ratchasima' },
      { name: 'Nong Bua Lam Phu', th: 'หนองบัวลำภู', value: 'nong_bua_lam_phu' },
      { name: 'Nong Khai', th: 'หนองคาย', value: 'nong_khai' },
      { name: 'Roi Et', th: 'ร้อยเอ็ด', value: 'roi_et' },
      { name: 'Sakon Nakhon', th: 'สกลนคร', value: 'sakon_nakhon' },
      { name: 'Si Sa Ket', th: 'ศรีสะเกษ', value: 'si_sa_ket' },
      { name: 'Surin', th: 'สุรินทร์', value: 'surin' },
      { name: 'Ubon Ratchathani', th: 'อุบลราชธานี', value: 'ubon_ratchathani' },
      { name: 'Udon Thani', th: 'อุดรธานี', value: 'udon_thani' },
      { name: 'Yasothon', th: 'ยโสธร', value: 'yasothon' },
    ],
  },
  {
    name: 'South',
    th: 'ภาคใต้',
    value: 'south',
    provinces: [
      { name: 'Chumphon', th: 'ชุมพร', value: 'chumphon' },
      { name: 'Krabi', th: 'กระบี่', value: 'krabi' },
      { name: 'Nakhon Si Thammarat', th: 'นครศรีธรรมราช', value: 'nakhon_si_thammarat' },
      { name: 'Narathiwat', th: 'นราธิวาส', value: 'narathiwat' },
      { name: 'Pattani', th: 'ปัตตานี', value: 'pattani' },
      { name: 'Phangnga', th: 'พังงา', value: 'phangnga' },
      { name: 'Phatthalung', th: 'พัทลุง', value: 'phatthalung' },
      { name: 'Phuket', th: 'ภูเก็ต', value: 'phuket' },
      { name: 'Ranong', th: 'ระนอง', value: 'ranong' },
      { name: 'Satun', th: 'สตูล', value: 'satun' },
      { name: 'Songkhla', th: 'สงขลา', value: 'songkhla' },
      { name: 'Surat Thani', th: 'สุราษฎร์ธานี', value: 'surat_thani' },
      { name: 'Trang', th: 'ตรัง', value: 'trang' },
      { name: 'Yala', th: 'ยะลา', value: 'yala' },
    ],
  },
  {
    name: 'West',
    th: 'ภาคตะวันตก',
    value: 'west',
    provinces: [
      { name: 'Kanchanaburi', th: 'กาญจนบุรี', value: 'kanchanaburi' },
      { name: 'Phetchaburi', th: 'เพชรบุรี', value: 'phetchaburi' },
      { name: 'Prachuap Khiri Khan', th: 'ประจวบคีรีขันธ์', value: 'prachuap_khiri_khan' },
      { name: 'Ratchaburi', th: 'ราชบุรี', value: 'ratchaburi' },
      { name: 'Suphan Buri', th: 'สุพรรณบุรี', value: 'suphan_buri' },
    ],
  },
];

    