
export const regions = [
  {
    name: 'Central',
    value: 'central',
    provinces: [
      { name: 'Ang Thong', value: 'ang_thong' },
      { name: 'Bangkok', value: 'bangkok' },
      { name: 'Chai Nat', value: 'chai_nat' },
      { name: 'Lop Buri', value: 'lop_buri' },
      { name: 'Nakhon Nayok', value: 'nakhon_nayok' },
      { name: 'Nakhon Pathom', value: 'nakhon_pathom' },
      { name: 'Nonthaburi', value: 'nonthaburi' },
      { name: 'Pathum Thani', value: 'pathum_thani' },
      { name: 'Phra Nakhon Si Ayutthaya', value: 'phra_nakhon_si_ayutthaya' },
      { name: 'Samut Prakan', value: 'samut_prakan' },
      { name: 'Samut Sakhon', value: 'samut_sakhon' },
      { name: 'Samut Songkhram', value: 'samut_songkhram' },
      { name: 'Saraburi', value: 'saraburi' },
      { name: 'Sing Buri', value: 'sing_buri' },
    ],
  },
  {
    name: 'East',
    value: 'east',
    provinces: [
      { name: 'Chachoengsao', value: 'chachoengsao' },
      { name: 'Chanthaburi', value: 'chanthaburi' },
      { name: 'Chon Buri', value: 'chon_buri' },
      { name: 'Prachin Buri', value: 'prachin_buri' },
      { name: 'Rayong', value: 'rayong' },
      { name: 'Sa Kaeo', value: 'sa_kaeo' },
      { name: 'Trat', value: 'trat' },
    ],
  },
  {
    name: 'North',
    value: 'north',
    provinces: [
      { name: 'Chiang Mai', value: 'chiang_mai' },
      { name: 'Chiang Rai', value: 'chiang_rai' },
      { name: 'Kamphaeng Phet', value: 'kamphaeng_phet' },
      { name: 'Lampang', value: 'lampang' },
      { name: 'Lamphun', value: 'lamphun' },
      { name: 'Mae Hong Son', value: 'mae_hong_son' },
      { name: 'Nakhon Sawan', value: 'nakhon_sawan' },
      { name: 'Nan', value: 'nan' },
      { name: 'Phayao', value: 'phayao' },
      { name: 'Phetchabun', value: 'phetchabun' },
      { name: 'Phichit', value: 'phichit' },
      { name: 'Phitsanulok', value: 'phitsanulok' },
      { name: 'Phrae', value: 'phrae' },
      { name: 'Sukhothai', value: 'sukhothai' },
      { name: 'Tak', value: 'tak' },
      { name: 'Uthai Thani', value: 'uthai_thani' },
      { name: 'Uttaradit', value: 'uttaradit' },
    ],
  },
  {
    name: 'Northeast',
    value: 'northeast',
    provinces: [
      { name: 'Amnat Charoen', value: 'amnat_charoen' },
      { name: 'Bueng Kan', value: 'bueng_kan' },
      { name: 'Buri Ram', value: 'buri_ram' },
      { name: 'Chaiyaphum', value: 'chaiyaphum' },
      { name: 'Kalasin', value: 'kalasin' },
      { name: 'Khon Kaen', value: 'khon_kaen' },
      { name: 'Loei', value: 'loei' },
      { name: 'Maha Sarakham', value: 'maha_sarakham' },
      { name: 'Mukdahan', value: 'mukdahan' },
      { name: 'Nakhon Phanom', value: 'nakhon_phanom' },
      { name: 'Nakhon Ratchasima', value: 'nakhon_ratchasima' },
      { name: 'Nong Bua Lam Phu', value: 'nong_bua_lam_phu' },
      { name: 'Nong Khai', value: 'nong_khai' },
      { name: 'Roi Et', value: 'roi_et' },
      { name: 'Sakon Nakhon', value: 'sakon_nakhon' },
      { name: 'Si Sa Ket', value: 'si_sa_ket' },
      { name: 'Surin', value: 'surin' },
      { name: 'Ubon Ratchathani', value: 'ubon_ratchathani' },
      { name: 'Udon Thani', value: 'udon_thani' },
      { name: 'Yasothon', value: 'yasothon' },
    ],
  },
  {
    name: 'South',
    value: 'south',
    provinces: [
      { name: 'Chumphon', value: 'chumphon' },
      { name: 'Krabi', value: 'krabi' },
      { name: 'Nakhon Si Thammarat', value: 'nakhon_si_thammarat' },
      { name: 'Narathiwat', value: 'narathiwat' },
      { name: 'Pattani', value: 'pattani' },
      { name: 'Phangnga', value: 'phangnga' },
      { name: 'Phatthalung', value: 'phatthalung' },
      { name: 'Phuket', value: 'phuket' },
      { name: 'Ranong', value: 'ranong' },
      { name: 'Satun', value: 'satun' },
      { name: 'Songkhla', value: 'songkhla' },
      { name: 'Surat Thani', value: 'surat_thani' },
      { name: 'Trang', value: 'trang' },
      { name: 'Yala', value: 'yala' },
    ],
  },
  {
    name: 'West',
    value: 'west',
    provinces: [
      { name: 'Kanchanaburi', value: 'kanchanaburi' },
      { name: 'Phetchaburi', value: 'phetchaburi' },
      { name: 'Prachuap Khiri Khan', value: 'prachuap_khiri_khan' },
      { name: 'Ratchaburi', value: 'ratchaburi' },
      { name: 'Suphan Buri', value: 'suphan_buri' },
    ],
  },
];
